version: "3.9"

services:
  api:
    container_name: api
    image: clean-node-api
    command: npm run debug
    build:
      dockerfile: .docker/api/Dockerfile.dev
      context: ./
    ports:
      - "5050:5050"
      - "9222:9222"
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    env_file: .env.local
    depends_on:
      - database-mongo

  database-mongo:
    container_name: database-mongo
    restart: always
    image: mongo:4.4.6-bionic
    env_file: .env.local
    volumes: 
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express-interface
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env.local
    depends_on:
      - database-mongo

volumes: 
  mongodb-data: