FROM node:16-alpine

LABEL org.opencontainers.image.authors="leonardopliski@gmail.com"

WORKDIR /usr/src/app

COPY ./package*.json .

RUN npm install --only=prod

COPY ./dist ./dist

EXPOSE 5050

CMD ["npm", "run", "start"]
